// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiGasolineras.Models
{
    public partial class ComunidadesAutonomasProvinciasMunicipio
    {
        public ComunidadesAutonomasProvinciasMunicipio()
        {
            EstacionesServicios = new HashSet<EstacionesServicio>();
        }

        public int IDMunicipio { get; set; }
        public int IDProvincia { get; set; }
        public string Municipio { get; set; }
        public DateTime fecha_alta { get; set; }
        public DateTime fecha_modificacion { get; set; }
        public int? IdUsuarioModificacion { get; set; }

        public virtual ICollection<EstacionesServicio> EstacionesServicios { get; set; }
    }
}