// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace ApiGasolineras.Models
{
    public partial class EstacionesServicio
    {
        public int IDEESS { get; set; }
        [JsonProperty("C.P.")]
        public int? CP { get; set; }
        public string Dirección { get; set; }
        public string Horario { get; set; }
        public string Latitud { get; set; }
        public string Localidad { get; set; }
        [JsonProperty("Longitud (WGS84)")]
        public string Longitud_WGS84 { get; set; }
        public string Margen { get; set; }
        [JsonProperty("Precio Biodiesel")]
        public decimal? Precio_Biodiesel { get; set; }
        [JsonProperty("Precio Bioetanol")]
        public decimal? Precio_Bioetanol { get; set; }
        [JsonProperty("Precio Gas Natural Comprimido")]
        public decimal? Precio_Gas_Natural_Comprimido { get; set; }
        [JsonProperty("Precio Gas Natural Licuado")]
        public decimal? Precio_Gas_Natural_Licuado { get; set; }
        [JsonProperty("Precio Gases Licuados del petróleo")]
        public decimal? Precio_Gases_licuados_del_petróleo { get; set; }
        [JsonProperty("Precio Gasoleo A")]
        public decimal? Precio_Gasoleo_A { get; set; }
        [JsonProperty("Precio Gasoleo B")]
        public decimal? Precio_Gasoleo_B { get; set; }
        [JsonProperty("Precio Gasoleo Premium")]
        public decimal? Precio_Gasoleo_Premium { get; set; }
        [JsonProperty("Precio Gasolina 95 E10")]
        public decimal? Precio_Gasolina_95_E10 { get; set; }
        [JsonProperty("Precio Gasolina 95 E5")]
        public decimal? Precio_Gasolina_95_E5 { get; set; }
        [JsonProperty("Precio Gasolina 95 E5 Premium")]
        public decimal? Precio_Gasolina_95_E5_Premium { get; set; }
        [JsonProperty("Precio Gasolina 98 E10")]
        public decimal? Precio_Gasolina_98_E10 { get; set; }
        [JsonProperty("Precio Gasolina 98 E5")]
        public decimal? Precio_Gasolina_98_E5 { get; set; }
        [JsonProperty("Precio Hidrogeno")]
        public decimal? Precio_Hidrogeno { get; set; }
        public string Remisión { get; set; }
        public string Rótulo { get; set; }
        [JsonProperty("Tipo Venta")]
        public string Tipo_Venta { get; set; }
        public int IDMunicipio { get; set; }
        public int IDProvincia { get; set; }
        public int IDCCAA { get; set; }

        public virtual ComunidadesAutonoma IDCCAANavigation { get; set; }
        public virtual ComunidadesAutonomasProvinciasMunicipio IDMunicipioNavigation { get; set; }
        public virtual ComunidadesAutonomasProvincia IDProvinciaNavigation { get; set; }
    }
}