// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiGasolineras.Models
{
    public partial class TiposCombustible
    {
        public TiposCombustible()
        {
            Coches = new HashSet<Coch>();
        }

        public int IdTipoCombustible { get; set; }
        public string codref { get; set; }
        public string combustible { get; set; }
        public DateTime fecha_alta { get; set; }
        public DateTime fecha_modificacion { get; set; }
        public int? IdUsuarioModificacion { get; set; }

        public virtual ICollection<Coch> Coches { get; set; }
    }
}